no_project_mount: true
hooks:
  post-start:
    - exec-host: ddev mutagen start
  pre-stop:
    - exec-host: ddev mutagen stop
    - exec-host: "rsync -azP -aR --exclude '.ddev*' . .ddev/project-stopped --delete --quiet"

  # Backup files before starting project
  pre-exec:
    - exec-host: "rsync -azP -aR --exclude '.ddev*' . .ddev/project-stopped --delete --quiet"
