no_project_mount: true
hooks:
  # Start project
  post-start:
    - exec-host: ddev mutagen run
  # Backup and stop project
  pre-stop:
    - exec-host: ddev mutagen backup
    - exec-host: ddev mutagen stop
