#!/bin/bash

## Description: Runs mutagen on the current project
## Usage: mutagen
## Example: "ddev mutagen"

END="$(tput sgr0)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
RED="$(tput setaf 1)"

function require_program {
    if ! type "$1" > /dev/null 2>&1; then
        echo "${RED}$1 is required. Please install it and try again.${END}"
        exit 1
    fi
}

require_program "mutagen"

# Prevent invalid session name errors.
SANITIZED_SITE_NAME=${DDEV_SITENAME//[^a-zA-Z0-9]/}

function mutagen_sync_create() {
  mutagen sync create . docker://ddev-${DDEV_SITENAME}-web/var/www/html --ignore-vcs --ignore=.ddev/project-stopped,.idea --sync-mode=two-way-resolved --symlink-mode=posix-raw --name="$SANITIZED_SITE_NAME"
}

# Wait for the initial sync process to complete, watch for errors
# Return when ready.
function initial_sync() {

    echo "${YELLOW}Waiting for initial sync to complete...${END}"
    while true; do
        if mutagen sync list "$SANITIZED_SITE_NAME" | grep "Last error"; then
            echo "${RED}Mutagen sync has errored -- check 'mutagen sync list $SANITIZED_SITE_NAME' for the problem${END}"
            break
        fi
        if mutagen sync list "$SANITIZED_SITE_NAME" | grep "Status: Watching for changes"; then
            echo "${GREEN}Initial mutagen sync has completed!${END}"
            break
        fi
    done
}

# Make sure the mutagen daemon is running.
function mutagen_daemon_start() {
    mutagen daemon start 2>/dev/null
    echo "${GREEN}Mutagen daemon started...${END}"
}

# Create the sync process from the ddev project name.
function mutagen_create_sync_filename() {
    echo "$SANITIZED_SITE_NAME" > ${DDEV_APPROOT}/.ddev/.mutagen-sync-name
}


if [ "$1" == "start" ]; then

      # Don't recreate mutagen sync if it already exists.
      if [ -f ".ddev/.mutagen-sync-name" ]; then
          echo "${RED}Mutagen sync appears to already be running{$END}"
          exit 0
      fi

      # Clear out the test files that are bundled with the web container.
      ddev . --dir /var/www rm phpstatus.php
      ddev . --dir /var/www/html rm -rf test
      ddev . --dir /var/www/html rm -rf index.html

      mutagen_daemon_start


      if ! mutagen sync list "$SANITIZED_SITE_NAME" 2>/dev/null; then
        mutagen_sync_create
      fi

      initial_sync

fi

if [ "$1" == "stop" ]; then

    # Copy and move sync name. Used for validation to resume project
    #cp "${DDEV_APPROOT}/.ddev/.mutagen-sync-name" "${DDEV_APPROOT}/.ddev/.mutagen-sync-name-stopped"
    rm -rf "${DDEV_APPROOT}/.ddev/.mutagen-sync-name"

    echo "${YELLOW}Terminate mutagen sync process...${END}"
    mutagen sync terminate "$SANITIZED_SITE_NAME"
    mutagen daemon stop

fi
