#!/bin/bash

## Description: Runs mutagen on the current project
## Usage: mutagen
## Example: "ddev mutagen"

END="$(tput sgr0)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
RED="$(tput setaf 1)"

function require_program {
    if ! type "$1" > /dev/null 2>&1; then
        echo "${RED}$1 is required. Please install it and try again.${END}"
        exit 1
    fi
}

require_program "mutagen"

# Prevent invalid session name errors.
SANITIZED_SITE_NAME=${DDEV_SITENAME//[^a-zA-Z0-9]/}

function mutagen_sync_create() {
  mutagen sync create . docker://ddev-${DDEV_SITENAME}-web/var/www/html --ignore-vcs --ignore=.ddev/project-stopped,.idea --sync-mode=two-way-resolved --symlink-mode=posix-raw --name="$SANITIZED_SITE_NAME"
}

# Wait for the initial sync process to complete, watch for errors
# Return when ready.
function initial_sync() {

    echo "${YELLOW}Waiting for initial sync to complete...${END}"
    while true; do
        if mutagen sync list "$SANITIZED_SITE_NAME" | grep "Last error"; then
            echo "${RED}Mutagen sync has errored -- check 'mutagen sync list $SANITIZED_SITE_NAME' for the problem${END}"
            break
        fi
        if mutagen sync list "$SANITIZED_SITE_NAME" | grep "Status: Watching for changes"; then
            echo "${GREEN}Initial mutagen sync has completed!${END}"
            break
        fi
        sleep 3
    done
}

# Make sure the mutagen daemon is running.
# If the daemon is already running, this will fail, but that's okay.
function mutagen_daemon_start() {
    mutagen daemon start 2>/dev/null
    echo "${GREEN}Mutagen daemon started...${END}"
}

# Create the sync process from the ddev project name.
function mutagen_create_sync_filename() {
    echo "$SANITIZED_SITE_NAME" > ${DDEV_APPROOT}/.ddev/.mutagen-sync-name
}

# Synchronize backup folder to host
# Create a new mutagen session
function rsync_project() {

    # Move folders/files if folder has backup files
    if [[ -d ".ddev/project-stopped" && -n "$(ls -A .ddev/project-stopped/)" ]]; then
        echo "${YELLOW}Sync [project-stopped] backup-files into root...${END}"
        rsync -azP --del --exclude '.ddev/*' .ddev/project-stopped/ ./ --quiet

        # Clear out the test files that are bundled with the web container.
        ddev . --dir /var/www/html rm -rf index.html
        ddev . --dir /var/www/html rm -rf test/

        mutagen_daemon_start
        mutagen_sync_create
        initial_sync
    else
      echo "${RED}[!] No files from backup folder${END}"
    fi

}


if [ "$1" == "start" ]; then

      # Resume from backup files
      if [[ -f "${DDEV_APPROOT}/.ddev/.mutagen-sync-name-stopped" && -f "${DDEV_APPROOT}/.ddev/.mutagen-sync-name" ]]; then

        if ! mutagen sync list "$SANITIZED_SITE_NAME" 2>/dev/null; then
            rsync_project
            exit
        fi

        # Reset mutagen sync X
        mutagen sync reset "$SANITIZED_SITE_NAME"
        rm "${DDEV_APPROOT}"/.ddev/.mutagen-sync-name-stopped
        initial_sync
        sleep 3
        exit
      fi


      ddev exec --dir /var/www rm -f phpstatus.php
      mutagen_daemon_start
      if [ ! -f "${DDEV_APPROOT}/.ddev/.mutagen-sync-name" ]; then
        mutagen_create_sync_filename
      fi

      if ! mutagen sync list "$SANITIZED_SITE_NAME" 2>/dev/null; then
          mutagen_sync_create
          initial_sync
      else
        rsync_project
      fi
fi

if [ "$1" == "stop" ]; then

    # Copy and move sync name. Used for validation to resume project
    cp ${DDEV_APPROOT}/.ddev/.mutagen-sync-name ${DDEV_APPROOT}/.ddev/.mutagen-sync-name-stopped

    # Move host files/dir to "save-directory"
    # echo "${GREEN}Wait: Backing up files to resume project later...${END}"
    # rsync -azP -aR --exclude '.ddev*' . .ddev/project-stopped --delete --quiet

    echo "${YELLOW}Terminate mutagen sync process...${END}"
    mutagen sync terminate "$SANITIZED_SITE_NAME"

fi
